kind: pipeline
name: default

steps:
    - name: build
      image: node:18-alpine3.14
      commands:
          - npm install --registry=https://registry.npm.taobao.org
          - npm run build

    - name: push-harbor
      image: plugins/docker
      settings:
          repo: 192.168.1.193:5011/dev/react_vite_ts
          registry: 192.168.1.193:5011
          username:
              from_secret: harbor_name
          password:
              from_secret: harbor_password
          tags:
              - dev
      when:
          event: ["custom"]
